### ISSUE TITLE
Enumerazione `esito` /rpp implementata nelle API Backoffice diversa da quella descritta nell'OpenAPI

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#156]
**Descrizione del Bug**
Nel descrittore OpenAPI del servizio Backoffice, il filtro `esito` della risorsa `rpp` viene descritto come segue
```yaml
    esitoRpt:
      example: ESEGUITO
      type: string
      enum:
        - IN_CORSO
        - RIFIUTATO
        - ESEGUITO
        - NON_ESEGUITO
        - ESEGUITO_PARZIALE
        - DECORRENZA
        - DECORENNZA_PARZIALE
```
mentre i valori accettati sono `PAGAMENTO_ESEGUITO`, ed altri

**Come riprodurlo:**
Effettuare una ricerca filtrando per esito

**Risultato atteso:**
Il filtro deve funzionare con i valori indicati nel descrittore OpenAPI, mentre se viene indicato un valore non previsto, deve essere ritornato un errore che indica i valori possibili:

```json
{
  "categoria": "RICHIESTA",
  "codice": "SINTASSI",
  "descrizione": "Richiesta non valida",
  "dettaglio": "Codifica inesistente per esito. Valore fornito [PAGAMENTO_ESEGUITO] valori possibili {ESEGUITO, ...}"
}
```
