### ISSUE TITLE
Gestione dati di contabilita in riconciliazione

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#309]
**Necessità:**
Aggiungere ai dati della pendenza i dati necessari alla contabilità da restituire a valle della riconciliazione

**Soluzione:**
Aggiungere alla voce_pendenza un campo `contabilita` opzionale di tipo lista con le seguenti informazioni:

- ufficio: [stringa max 64] rappresenta il codice dell’ufficio (opz.)
- capitolo: [stringa max 64] codice del capitolo (obb.)
- anno_esercizio: [anno in formato yyyy] anno di esercizio (obb.)
- accertamento: [stringa max 64] codice dell’accertamento. (opz.)
- anno_accertamento: [anno in formato yyyy] anno accertamento (opz.)
- sub_accertemento: [stringa max 64] codice dell’accertamento se contabilita di terze parti. (opz.)
- siope: [stringa max 64] codice siope dell'entrata (opz.)
- importo: numerico con due decimali (obb.)
- cod_gestionale_ente: [stringa max 256] codice contabilita' utilizzato dal gestionale dell'ente (opz.)

**Comment by nardil** [comment]
Nell'acquisizione della posizione, se valorizzata la struttura `contabilita`, viene controllato che la somma degli importi corrisponda a quella della voce.

**Comment by nardil** [comment]
Vista l'etereogenita' dei dati contabili previsti dalle varie piattaforme (MyPIVOT, HyperSIC, etc...) si modifica l'elemento contabilita per migliorarne l'estensibilita:

```yaml
    contabilita:
      type: object
      properties:
        quotaContabile:
          type: array
          items: 
            type: object
            properties:
              annoEsercizio:
                type: number
                description: Anno di esercizio
                example: 2020
              capitolo:
                type: string
                description: Codice del capitolo
                maxLength: 64
              accertamento:
                type: string
                description: Codice dell’accertamento
                maxLength: 64        
              proprietaCustom:
                type: object
                description: Dati specifici del gestionale di contabilità
          proprietaCustom:
            type: object
            description: Dati specifici del gestionale di contabilità
```
