### ISSUE TITLE
Supporto agli allegati di una Pendenza

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#482]
**Necessità:**
Allegare file binari alla pendenza.

**Soluzione:**

Aggiungere all'oggetto Pendenza l'attributo `allegati`
```yaml
allegati:
  type: array
  items:
    type: object 
    required: 
      - nome
      - contenuto            
    properties: 
      nome:
        type: string
        description: nome del file
      tipo:
        type: string
        description: mime type del file
        default: "application/octet-stream"
      descrizione:
        type: string
        description: descrizione del file
      contenuto: 
        oneOf:
        - type: string
          format: byte
          description: contenuto del file
        - type: string
          description: path per accedere al file, nella forma /allegati/{id}
```

In inserimento o aggiornamento di una nuova pendenza, gli allegati vengono memorizzati in una tabella separata dalla pendenza con un riferimento ad essa indicizzato (foreign key). Quando la pendenza viene letta, nel `contenuto` degli elementi `allegato` deve essere indicato il path alla risorsa `/allegati/{id}` non il contenuto stesso. 

La risorsa `/allegati/{id}` deve essere autorizzata solo se l'utenza che la richiede e' autorizzata in lettura alla pendenza associata.
