### ISSUE TITLE
Errata definizione del campo prossimiRisultati

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#561]
**Descrizione del Bug**

Negli OpenAPI dei servizi il campo `prossimiRisultati` e' definito come segue:

```yaml
prossimiRisultati:
  type: string
  format: integer
  example: '/risorsa?pagina=2' 
```

ma il format `integer` non e' corretto, ne' formalizzato dallo standard OpenAPI

**Risultato atteso:**

Rimuovere il format dalla definizione del field `prossimiRisultati`
